on: [push]

jobs:
  setup_deepsomatic:
    runs-on: ubuntu-latest
    name: DeepSomatic docker setup
    steps:
      - name: Setup docker
        id: deepsomatic
        uses: soymintc/deepvariant@v1

